name: MineralUI
main: KienMC\Mineral\Main
api: 5.0.0
version: 0.0.1
author:
- KienDev
description: Plugin MineralUI Code By KienDev
virions: ["libPiggyEconomy"]
commands:
  mineral:
    description: "Open Menu Mineral"
    permission: mineral.cmd
    aliases: ["mr"]
permissions:
  mineral.cmd:
    default: true
